### ISSUE TITLE
vue-image-lazy-load 正常工作吗？

### ISSUE THREAD

**Issue by yangliguo7** [Vitaminaq/cfsw-vue-cli3.0#1]
hi~，我也是用vite+ssr进行图片懒加载，但是我按照你的cfsw-vue-cli3.0-vue3.0-ssr工程进行配置vue-image-lazy-load，但是并没有进行图片懒加载，它可以正常工作吗?  我在vue的issue上看到你的问题，看到你解决了
我得代码
```
in entry.clinet.js

router.isReady().then(() => {
    app.use(VueImageLazyLoad).mount('#app');
  }); 
```
```
服务端的html
<img src=xxx vue-image-lazy-load > 
```
```
in vite.config.js

  plugins: [
    vue({
      template: {
        ssr: true,
        compilerOptions: {
          directiveTransforms: {
            'img-lazy-load': ssrTransformCustomDir,
          },
        },
      },
    }),
  ]
```

但是他并没进行懒加载图片，感谢回复

**Comment by Vitaminaq** [comment]
ssrTransformCustomDir方法里面加了needRuntime: true没

**Comment by yangliguo7** [comment]
感谢回复。咱们使用场景不一样，我们是node端获取富文本编辑器内容然后传给前端用v-html渲染。所以指令在v-html是不会识别的。然后我手写了一个懒加载。

**Comment by Vitaminaq** [comment]
哈哈，强
![89822D38AB234E4A2EC1836C3E79B89E](https://user-images.githubusercontent.com/22076916/148709785-f5d0d6c5-3379-4c47-8af1-5705e3850343.png)
